all: main.out

main.out : main.o Headers.o disk.o TestCase1.o
	gcc -o main.out main.o Headers.o disk.o TestCase1.o

main.o : main.c Headers.h TestCase1.h
	gcc -c -o main.o main.c

Headers.o : Headers.c Headers.h
	gcc -c -o Headers.o Headers.c

disk.o : disk.c disk.h
	gcc -c -o disk.o disk.c

TestCase1.o : TestCase1.c TestCase1.h
	gcc -c -o TestCase1.o TestCase1.c

clean:
	rm *.out *.o
